export interface SeedAsset {
  alpaca_id: string;
  class: string;
  exchange?: string | null;
  symbol: string;
  name: string;
  status?: string | null;
  tradable?: boolean;
  marginable?: boolean;
  shortable?: boolean;
  easy_to_borrow?: boolean;
  fractionable?: boolean;
  attributes?: readonly string[] | null; // ← key: explicit readonly string[] or null
  // Add other fields only if you actually use them (maintenance_margin_* etc.)
}

export const seedAlpacaAssets = [
  {
    alpaca_id: "b0b6dd9d-8b9b-48a9-ba46-b9d54906e415",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "AAPL",
    name: "Apple Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "09a51104-980a-47b6-ad4d-e4f04059be4a",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "ABBV",
    name: "ABBVIE INC.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "a097c03a-7ebe-4de6-b729-a82370cd2a6e",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "ABT",
    name: "Abbott Laboratories",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "6eace613-5882-4eca-8635-d1c41ee9e260",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "ACN",
    name: "Accenture PLC",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "2ac633b5-b3a7-4ba6-975d-f0f1e12dd1e4",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "ADBE",
    name: "Adobe Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "6ca2e51d-21df-4ff0-a134-abfdbe084142",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "ADP",
    name: "Automatic Data Processing, Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "03fb07bb-5db1-4077-8dea-5d711b272625",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "AMD",
    name: "Advanced Micro Devices, Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "f801f835-bfe6-4a9d-a6b1-ccbb84bfd75f",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "AMZN",
    name: "Amazon.com, Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "6082378d-ba94-4bb7-a49e-ebe714131ca8",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "ASML",
    name: "ASML Holding N.V. New York Registry Shares",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "7a8b4fcf-0622-47ef-8541-de7f70ffc0c4",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "AVGO",
    name: "Broadcom Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "49b90cdc-f6f5-4a7c-807a-ed172e6017af",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "AXP",
    name: "American Express Company",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "3bed4fb2-4093-4433-b887-770ae3defd3a",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "BA",
    name: "Boeing Company",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "061588a3-d70b-4b9c-a3f6-636aaa16acc4",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "BAC",
    name: "Bank of America Corporation",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "c50070cd-18b4-4f29-ae0f-f192e4cc4553",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "BKNG",
    name: "Booking Holdings Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "ad22d1ca-8bfc-45cc-ae7f-5f091bbc8c7c",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "BMY",
    name: "Bristol-Myers Squibb Co.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "71bb19d0-6c5f-4881-9552-33224badd810",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "BRK.B",
    name: "BERKSHIRE HATHAWAY Class B",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "2652a688-e44c-469e-92f8-8ece2594d4c0",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "BSX",
    name: "Boston Scientific Corp.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "c9cc0895-bbca-47fb-be9e-e70e4a7eb94d",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "BX",
    name: "Blackstone Inc.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "36c8d04d-be51-476c-9382-0b6ea3bf1a26",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "C",
    name: "Citigroup Inc.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "e7535ed9-c182-41ef-80f6-ee08f4166b6c",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "CAT",
    name: "Caterpillar Inc.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "2453845c-4785-46de-b332-6ee2438da196",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "CB",
    name: "Chubb Limited",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "16af176c-d616-41d8-8a5a-b40c326e050e",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "CI",
    name: "The Cigna Group",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "5ddc1e60-daca-45da-b2de-f3ee597e60bc",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "CMCSA",
    name: "Comcast Corporation Class A Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "bc05b0d9-3b5d-4530-b500-3af2accbd71e",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "CME",
    name: "CME Group Inc. Class A Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "705363ac-b8c6-4d0e-9c9b-a343f3103de6",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "COP",
    name: "ConocoPhillips",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "1f888138-e413-4939-b16b-bdd08bb4debd",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "COST",
    name: "Costco Wholesale Corporation Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "cf80d13f-470c-4947-8593-c5e098aeba4e",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "CRM",
    name: "Salesforce, Inc.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "9ec078b1-5167-4d3d-908c-a1e49be367f1",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "CSCO",
    name: "Cisco Systems, Inc. Common Stock (DE)",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "186997ab-b63c-439b-bf62-72275d1c4c27",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "CVX",
    name: "Chevron Corporation",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "c00df298-9fb1-49e6-b9d9-92e3749ec5be",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "DE",
    name: "Deere & Company",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "42f6d400-741b-4a18-ae61-73faae71e2cb",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "DHR",
    name: "Danaher Corporation",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "2f34c0b3-a4aa-4959-b52c-3c41b2c246c4",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "DIS",
    name: "The Walt Disney Company",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "267f9ea7-eb9a-41cd-946f-5fab57943f0a",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "ELV",
    name: "Elevance Health, Inc.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "f801bacd-b8a5-4478-8321-699c3c9984cb",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "EQIX",
    name: "Equinix, Inc. Common Stock REIT",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "d4806319-2c9c-48d6-bda3-aedb0178e83b",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "ETN",
    name: "Eaton Corporation, plc Ordinary Shares",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "0116ac5c-90bc-47a2-8bb4-0f4551521dc6",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "GE",
    name: "GE Aerospace",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "aa222c8c-5f60-4b88-bc73-7aaadf424628",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "GILD",
    name: "Gilead Sciences, Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "69b15845-7c63-4586-b274-1cfdfe9df3d8",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "GOOGL",
    name: "Alphabet Inc. Class A Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "064dd45f-7a58-452c-93f2-377f9a0cc7f2",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "GS",
    name: "Goldman Sachs Group Inc.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["ptp_with_exception", "fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "b6b1ea06-5d71-4146-be77-03f671788940",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "HD",
    name: "Home Depot, Inc.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "f48fc899-5da1-4687-a23b-515752d5e917",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "HON",
    name: "Honeywell International Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "21d40833-6d13-4031-9af3-02f6a516d791",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "IBM",
    name: "International Business Machines Corporation",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "dab97681-1775-47b8-922a-d23a4e50744d",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "ICE",
    name: "Intercontinental Exchange  Inc.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "0cf42aa3-9816-4f1f-aa84-6482ac9303e9",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "INTC",
    name: "Intel Corporation Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "cd1347d7-8add-49bd-acd1-4ffde9a4081b",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "INTU",
    name: "Intuit Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "ef9adcc6-6bce-452b-af5f-4a87e7f19131",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "JNJ",
    name: "Johnson & Johnson",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "e3047683-637a-4fb2-b71d-805cd6fec95d",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "c1fe01e7-c9b1-4b92-8c7a-32153021367e",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "KLAC",
    name: "KLA Corporation Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "3795cafe-fd54-4f66-a31e-66774be875ca",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "KO",
    name: "Coca-Cola Company",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "cbf869d9-873b-426a-bdea-37e0bc4250f9",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "LIN",
    name: "Linde plc Ordinary Shares",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "87266a27-1b34-47bd-b236-bd3a9f59b138",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "LLY",
    name: "Eli Lilly & Co.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "6ae1929e-adcd-4de1-9647-25763c8a4548",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "LMT",
    name: "Lockheed Martin Corp.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "2140998d-7f62-46f2-a9b2-e44350bd4807",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "MA",
    name: "Mastercard Incorporated",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "e077638f-a5c9-47e4-a7ce-2bfabf5ff698",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "MCD",
    name: "McDonald's Corporation",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "705ec4dc-73b9-42fc-8b17-d4e13c31cfae",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "MDLZ",
    name: "Mondelez International, Inc. Class A Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "1fc2849e-26d5-4f49-add6-2f913ded54c9",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "MDT",
    name: "Medtronic plc",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "fc6a5dcd-4a70-4b8d-b64f-d83a6dae9ba4",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "META",
    name: "Meta Platforms, Inc. Class A Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "4eb91cfa-4f8b-4df5-acb7-2f3434fa283f",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "MO",
    name: "Altria Group, Inc.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "0d56791f-7395-40fa-853b-7b852bd9a7bf",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "MRK",
    name: "Merck & Co., Inc.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "b6d1aa75-5c9c-4353-a305-9e2caa1925ab",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "MSFT",
    name: "Microsoft Corporation Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "1ef18995-5094-4f62-a5c5-e00168611152",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "MU",
    name: "Micron Technology, Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "bb2a26c0-4c77-4801-8afc-82e8142ac7b8",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "NFLX",
    name: "Netflix, Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "db00f7c3-19bb-42b6-9beb-79e92487f99e",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "NKE",
    name: "Nike, Inc.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "0ec9e18b-6dc2-43f7-a956-8d07bac7c08b",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "NOW",
    name: "SERVICENOW, INC.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "4ce9353c-66d1-46c2-898f-fce867ab0247",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "NVDA",
    name: "NVIDIA Corporation Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "0e0a8d50-17fe-44ce-b4ab-839cd5e63c4b",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "NVS",
    name: "Novartis AG",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "27982558-2464-4daf-bb2f-b3b728659884",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "ORCL",
    name: "Oracle Corp",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "ba1cc326-cf8d-4d7c-a49e-8b413555f3d0",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "PANW",
    name: "Palo Alto Networks, Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "7b7466c4-5066-4e3e-80e6-8da1c835ce56",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "PEP",
    name: "PepsiCo, Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "b0940983-b0c6-42f1-97d5-b1b580e4431b",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "PFE",
    name: "Pfizer Inc.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "f81a406b-a53c-4ea5-ab05-6fb92bfc6bd7",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "PG",
    name: "Procter & Gamble Company",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "b19c4863-d517-4472-9236-8864e50dfa3e",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "PM",
    name: "Philip Morris International Inc.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "24cbba8c-831b-44e2-8503-dd0c2ed7af8f",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "PYPL",
    name: "PayPal Holdings, Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "39be1334-06b6-4df2-a2f1-b21b942628d0",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "QCOM",
    name: "QUALCOMM Incorporated Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "5098a4d2-0917-4184-862c-17dbefde2ed4",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "REGN",
    name: "Regeneron Pharmaceuticals, Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "4d8f7f83-d998-4839-9134-38473cd13123",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "RTX",
    name: "RTX Corporation",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "55d586fd-4ccc-4c9c-9e07-4f1d18ed298f",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "SAP",
    name: "SAP SE",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "0a7deac5-2d75-4e54-9f66-51c1c6fad55b",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "SBUX",
    name: "Starbucks Corporation Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "1f868250-6f1d-4a57-9cd0-ac3f581a96e5",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "SCHW",
    name: "The Charles Schwab Corporation",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "5a71649b-e578-4229-81a3-d3a5c1351dd7",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "SO",
    name: "The Southern Company",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "10f7d07f-0811-42bf-a780-b4d4cb53eb91",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "SPGI",
    name: "S&P Global Inc.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "1c8746ac-5a25-4456-95e1-970ae6ade43c",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "SYK",
    name: "Stryker Corporation",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "1168e42c-a598-4ed9-8371-2033a0f6af54",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "TJX",
    name: "TJX Companies, Inc. (The)",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "092cb487-7467-4059-bf67-84ee072f8450",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "TM",
    name: "Toyota Motor Corporation American Depositary Shares (Each representing ten Ordinary Shares)",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "7f9df478-237c-45c8-bc80-c97a53478c37",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "TMUS",
    name: "T-Mobile US, Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "8ccae427-5dd0-45b3-b5fe-7ba5e422c766",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "TSLA",
    name: "Tesla, Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 50,
    margin_requirement_long: "50",
    margin_requirement_short: "50",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "626ce11f-1e10-488b-8d75-a3eff18d6d0f",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "TSM",
    name: "Taiwan Semiconductor Manufacturing Company Ltd.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "18bb7754-1ba4-4e24-8466-459b58589874",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "TTE",
    name: "TotalEnergies SE",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: false,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["has_options"],
  },
  {
    alpaca_id: "bea0f181-afd8-4bd2-9486-85d3fc2f10d7",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "UBER",
    name: "Uber Technologies, Inc.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "943bb7c3-0fb0-4088-9a37-62549b5dc528",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "UNH",
    name: "UNITEDHEALTH GROUP INCORPORATED (Delaware)",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "e28f2c45-0bb1-45c1-84e0-f8d1a98c4088",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "UNP",
    name: "Union Pacific Corp.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "b14caeab-f212-40ee-975a-38b9317e46b1",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "UPS",
    name: "United Parcel Service, Inc. Class B",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "4f5baf1e-0e9b-4d85-b88a-d874dc4a3c42",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "V",
    name: "VISA Inc.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "357a8404-f368-40a1-9356-3eb500f4f08a",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "VRTX",
    name: "Vertex Pharmaceuticals Incorporated Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "a54066ec-ebb0-4d1e-b7cf-cd84298515ec",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "VZ",
    name: "Verizon Communications",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "f9700a20-b0fe-4516-87c5-9d7b096d5539",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "WFC",
    name: "Wells Fargo & Co.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "3f3e0ff9-599f-4fec-8842-6bc53f5129a1",
    class: "us_equity",
    exchange: "NASDAQ",
    symbol: "WMT",
    name: "Walmart Inc. Common Stock",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
  {
    alpaca_id: "5344140c-ca01-4435-8a4a-217d4496bd35",
    class: "us_equity",
    exchange: "NYSE",
    symbol: "ZTS",
    name: "ZOETIS INC.",
    status: "active",
    tradable: true,
    marginable: true,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    maintenance_margin_requirement: 30,
    margin_requirement_long: "30",
    margin_requirement_short: "30",
    attributes: ["fractional_eh_enabled", "has_options"],
  },
];
